### ISSUE TITLE
can you give a success example

### ISSUE THREAD

**Issue by Eipgen** [lorenaav/Struc2Lammps#1]
I find the dependency of the code is confusion, I can't use code to transfer xyz file to lammps data.

**Comment by lorenaav** [comment]
You have to specify the box size and angles since most xyz files do not contain the information. 
What error do you get? Is it working with CIF files? Are all requirements met?

**Comment by Eipgen** [comment]
I use the  CIF file in the example, and the Error report is below, maybe the **nAtomtype**s and **types** are not corresponding .

```
User defined parameters:
File name:  data/sample_cellulose.cif
Box parameters in file?:  True
Input values (bondscale, force field, charge eq.):  1.1 Dreiding Gasteiger
True [0. 0. 0. 0. 0. 0. 0. 0. 0.] .cif
1 molecule converted
Creating bonds ...
1 molecule converted
OVITO sucessfully converted file
Box size parameters read:
x: 0.000 7.784
y: 0.000 8.147
z: 0.000 10.380
-0.9354899199 0.0 0.0 xy xz yz



Traceback (most recent call last):
  File "str2lmp.py", line 106, in <module>
    run_all(name, box_parameters, bondscale, ffield, charge, opath)
  File "str2lmp.py", line 76, in run_all
    createBonds.create_bonds(outfilelmpdat, outfilepdb, bondscale, lattice_in_file, boundaries)
  File "/home/jxiao/eQeq/Struc2Lammps/createBonds.py", line 19, in create_bonds
    create_lammps_in(outfilelmpdat, ntypes, outfilepdb, bondscale)_
  File "/home/jxiao/eQeq/Struc2Lammps/createBonds.py", line 166, in create_lammps_in
    f.write(createBondCommands.create_bonds_commands(lmpdatFile, outfilepdb, bondscale))
  File "/home/jxiao/eQeq/Struc2Lammps/createBondCommands.py", line 11, in create_bonds_commands
    commands = atom_type_groups_commands(infile, nAtomTypes, types)
  File "/home/jxiao/eQeq/Struc2Lammps/createBondCommands.py", line 43, in atom_type_groups_commands
    group_commands += 'group    {0} type {1} \n'.format(types[i], i+1)
IndexError: list index out of range
```

**Comment by Eipgen** [comment]
my python env packages is below:
```
ase @ file:///home/conda/feedstock_root/build_artifacts/ase_1638384343806/work
certifi==2022.9.24
click @ file:///home/conda/feedstock_root/build_artifacts/click_1651215140632/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
f90wrap @ file:///home/conda/feedstock_root/build_artifacts/f90wrap_1663178304720/work
Flask @ file:///home/conda/feedstock_root/build_artifacts/flask_1660054669620/work
fonttools @ file:///home/conda/feedstock_root/build_artifacts/fonttools_1663707884996/work
importlib-metadata==4.12.0
itsdangerous @ file:///home/conda/feedstock_root/build_artifacts/itsdangerous_1648147185463/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
kiwisolver @ file:///home/conda/feedstock_root/build_artifacts/kiwisolver_1657953088445/work
lammps @ file:///home/conda/feedstock_root/build_artifacts/lammps_1663738119057/work/python
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1648737551960/work
matplotlib @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-suite_1659031523330/work
munkres==1.1.4
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1649806299270/work
ovito==3.7.8
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1637239678211/work
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1660385854171/work
pybind11==2.10.0
pyeqeq==0.0.9
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1652235407899/work
PySide2==5.13.2
PySide6==6.2.4
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
quippy===NOT-A-GIT-REPOSITORY
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy_1637806658031/work
shiboken2==5.13.2
shiboken6==6.2.4
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
traits @ file:///home/conda/feedstock_root/build_artifacts/traits_1660549922321/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1656706066251/work
unicodedata2 @ file:///home/conda/feedstock_root/build_artifacts/unicodedata2_1649111917568/work
Werkzeug @ file:///home/conda/feedstock_root/build_artifacts/werkzeug_1660053523487/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1659400682470/work``
```

**Comment by Eipgen** [comment]
what's the version of the lammps, I find a error is 
`LAMMPS (16 Mar 2018)
ERROR: Illegal special_bonds command (../force.cpp:836)
Last command: special_bonds  lj 0.0 1.0 1.0 extra 10000`
